// ChatScreen, moved out of App.jsx on 2026-09-16 with the module-level
// helpers only it uses. App passes the state and callbacks it reads as
// one props object (chatProps in App.jsx); nothing here writes App state
// except through those callbacks.
import { COUNCIL_DECISION_OPTIONS } from "../profile/strategy-council.js";
import { renderMarkdownSafe } from "../chat/markdown.jsx";
import { t as tt } from "../i18n.js";
import DriftBanner from "../components/DriftBanner.jsx";
import DeadlineTracker from "../components/DeadlineTracker.jsx";
import CloseButton from "../components/CloseButton.jsx";
import NarrativeEditor from "../components/NarrativeEditor.jsx";
import CandidateRanker from "../components/CandidateRanker.jsx";
import SpikeFinder from "../components/SpikeFinder.jsx";
import CourseSequencer from "../components/CourseSequencer.jsx";
import TranscriptImportCard from "../components/TranscriptImportCard.jsx";



export default function ChatScreen(props) {
  const {
    agentStatus,
    budgetStatus,
    cancelPendingRequest,
    chatEnd,
    chatFiles,
    chatFilesExpanded,
    chatTextareaRef,
    clearChatFiles,
    councilDecisionType,
    deadlineRefreshKey,
    dismissTool,
    fileInputRef,
    folderInputRef,
    handleChatFilesSelect,
    handleExportData,
    importParsedTranscript,
    input,
    inputRef,
    loading,
    locale,
    messages,
    narrativeVersion,
    openTool,
    parseTranscriptText,
    pendingFile,
    removeChatFile,
    send,
    setChatFilesExpanded,
    setCouncilDecisionType,
    setInput,
    setNarrativeVersion,
    setPendingFile,
    setSNarrativeSaved,
    setSidebarOpen,
    sidebarOpen,
    targetSchools,
    user,
  } = props;
  return (
    <main className="cc-chat-main" style={{ flex:1,display:"flex",flexDirection:"column",minWidth:0 }}>
      <div style={{ padding:"10px 18px",borderBottom:"1px solid rgba(255,255,255,0.05)",display:"flex",alignItems:"center",gap:10,background:"rgba(255,255,255,0.015)",flexShrink:0 }}>
        <button onClick={()=>setSidebarOpen(!sidebarOpen)} style={{background:"none",border:"none",color:"#6a6a7a",cursor:"pointer",fontSize:16,padding:"4px 6px",borderRadius:6}}>{sidebarOpen?"◀":"▶"}</button>
        <span style={{ fontSize:16 }}>🎓</span>
        <div style={{flex:1}}>
          <span style={{fontSize:14,fontWeight:600}}>College Counselor</span>
          <span style={{fontSize:12,color:"#6a6a7a",marginLeft:8}}>{user?.name}</span>
        </div>
        <button onClick={handleExportData} style={{padding:"8px 12px",minHeight:36,borderRadius:8,border:"1px solid rgba(255,255,255,0.16)",background:"transparent",color:"#b7c1ce",fontSize:11,cursor:"pointer"}}>Export</button>
      </div>

      <div style={{ padding:"6px 18px",background:"rgba(55,138,221,0.04)",borderBottom:"1px solid rgba(55,138,221,0.08)",fontSize:10,color:"#6a8ab5",display:"flex",alignItems:"center",gap:6,flexShrink:0 }}>
        <span style={{fontSize:12}}>AI</span>
        <span>Responses are generated by AI and are advisory only. Verify official information with school counselors and institutional sources. Your data is encrypted and never sold.</span>
      </div>

      {/* ─── Round 1-5 chat-top status row ─── */}
      {/* DriftBanner self-fetches /api/narrative/drift; renders null when     */}
      {/* fresh / dismissed. Compact DeadlineTracker self-fetches and renders  */}
      {/* a chip only when overdue or due-in-7. Both are zero-noise when there */}
      {/* is nothing to surface, so the chat top stays clean for new students. */}
      <div style={{ padding:"8px 18px",display:"flex",gap:10,flexWrap:"wrap",flexShrink:0,alignItems:"center" }}>
        <DriftBanner locale={locale} refreshKey={narrativeVersion} onReview={() => openTool("candidates")} onWriteStory={() => openTool("narrative")} />
        <DeadlineTracker locale={locale} compact refreshKey={deadlineRefreshKey} />
      </div>

      <div role="log" aria-live="polite" aria-relevant="additions" style={{ flex:1,overflowY:"auto",padding:"16px 18px 0" }}>
        {messages.map((m,i)=>{
          // Inline tool cards (Edit story / Rank ECs / Spike Finder /
          // Course plan). Ephemeral, full-width, never sent to the model.
          if (m.role === "tool") {
            const toolTitleKey = {
              narrative: "narrative.title",
              candidates: "candidates.title",
              spike: "spike.title",
              courses: "courses.title",
              transcript_import: "transcript.title",
            }[m.tool] || "chat.modal.close";
            return (
              <div key={m.id||i} id={m.id||undefined} style={{marginBottom:14}}>
                <div style={{
                  background:"#101522", border:"1px solid rgba(255,255,255,0.08)",
                  borderRadius:14, padding:18, position:"relative",
                }}>
                  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:10}}>
                    <span style={{fontSize:10,color:"#6a6a7a",textTransform:"uppercase",letterSpacing:"0.07em"}}>
                      🛠 {tt(locale, toolTitleKey)}
                    </span>
                    <CloseButton label={tt(locale, "chat.modal.close")} onClick={()=>dismissTool(m.id)} style={{marginTop:-6,marginRight:-8}} />
                  </div>
                  {m.tool==="narrative" && (
                    <NarrativeEditor locale={locale} targetSchools={targetSchools} onSaved={()=>{ setSNarrativeSaved(true); setNarrativeVersion((v) => v + 1); }} />
                  )}
                  {m.tool==="candidates" && (
                    <CandidateRanker locale={locale} targetSchools={targetSchools} onWriteNarrative={()=>openTool("narrative")} />
                  )}
                  {m.tool==="spike" && (
                    <SpikeFinder locale={locale} targetSchools={targetSchools} onWriteNarrative={()=>openTool("narrative")} />
                  )}
                  {m.tool==="courses" && (
                    <CourseSequencer locale={locale} targetSchools={targetSchools} />
                  )}
                  {m.tool==="transcript_import" && (
                    <TranscriptImportCard file={m.file} onParse={parseTranscriptText} onImport={importParsedTranscript} />
                  )}
                </div>
              </div>
            );
          }
          return (
          <div key={i} style={{display:"flex",justifyContent:m.role==="user"?"flex-end":"flex-start",marginBottom:14}}>
            <div style={{maxWidth:"78%"}}>
              {/* Attached-file chips: compact icon + filename. The
                  full file contents go to the model (via modelContent)
                  but NEVER render in the chat — only these chips. */}
              {m.attachment && (() => {
                const ext = (n) => String(n||"").split(".").pop()?.toLowerCase() || "";
                const iconFor = (n) => {
                  const e = ext(n);
                  if (e === "pdf") return "📕";
                  if (["png","jpg","jpeg","webp","gif","heic","heif"].includes(e)) return "🖼️";
                  if (["doc","docx"].includes(e)) return "📘";
                  if (["xls","xlsx","csv","tsv"].includes(e)) return "📊";
                  if (["js","jsx","ts","tsx","py","go","rs","java","c","cpp","cs","rb","php","swift","html","css","json","yaml","yml","xml","sh"].includes(e)) return "📜";
                  if (["md","markdown","txt","rst","log"].includes(e)) return "📄";
                  return "📎";
                };
                // Build the list of filenames to chip. Multi-file
                // messages carry `.list`; single-file messages just
                // `.name`.
                const names = Array.isArray(m.attachment.list) && m.attachment.list.length
                  ? m.attachment.list
                  : (m.attachment.name ? [m.attachment.name] : []);
                if (!names.length) return null;
                const MAX_CHIPS = 6;
                const shown = names.slice(0, MAX_CHIPS);
                const overflow = names.length - shown.length;
                const chip = (label, key) => (
                  <span key={key} style={{
                    display:"inline-flex", alignItems:"center", gap:4,
                    padding:"3px 8px", borderRadius:6,
                    background:"rgba(255,255,255,0.10)",
                    border:"1px solid rgba(255,255,255,0.14)",
                    fontSize:11, color:"#e8eefc", maxWidth:200,
                  }}>
                    <span>{iconFor(label)}</span>
                    <span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap"}}>{label}</span>
                  </span>
                );
                return (
                  <div style={{marginBottom:5,display:"flex",alignItems:"center",gap:5,flexWrap:"wrap",justifyContent:m.role==="user"?"flex-end":"flex-start"}}>
                    {shown.map((nm, i) => chip(nm, i))}
                    {overflow > 0 && chip(`+${overflow} more`, "ovf")}
                  </div>
                );
              })()}
              {m.role==="user" ? (
                <div style={{padding:"12px 16px",borderRadius:"14px 14px 4px 14px",background:"linear-gradient(135deg,#378ADD,#667eea)",border:"none",fontSize:13.5,lineHeight:1.65,whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{m.content}</div>
              ) : (
                <div style={{padding:"12px 16px",borderRadius:"14px 14px 14px 4px",background:"rgba(255,255,255,0.04)",border:"1px solid rgba(255,255,255,0.05)",fontSize:13.5,lineHeight:1.65,wordBreak:"break-word"}}>{renderMarkdownSafe(m.content)}</div>
              )}
            </div>
          </div>
          );
        })}
        {loading && (
          <div style={{marginBottom:14}}>
            <div style={{padding:"12px 16px",borderRadius:"14px 14px 14px 4px",background:"rgba(255,255,255,0.04)",border:"1px solid rgba(255,255,255,0.05)",fontSize:13,color:"#6a6a7a",display:"flex",alignItems:"center",gap:8}}>
              <span>{agentStatus.phase || "Thinking..."}</span>
              <span style={{display:"inline-flex",gap:3}}>{[0,1,2].map(j=>(<span key={j} style={{width:5,height:5,borderRadius:"50%",background:"#63b3ed",animation:`pulse2 1.2s ease-in-out ${j*0.2}s infinite`}} />))}</span>
              {agentStatus.active !== "strategy_council" && (
                <button onClick={cancelPendingRequest} style={{marginLeft:"auto",padding:"4px 12px",borderRadius:8,border:"1px solid rgba(245,101,101,0.3)",background:"transparent",color:"#f56565",fontSize:11,cursor:"pointer",transition:"all 0.15s"}}>Cancel</button>
              )}
            </div>
          </div>
        )}
        <div ref={chatEnd} />
      </div>

      {/* File attachment preview ABOVE the textarea.
          UX rule: ≤4 files AND no folder paths → render every file
          as its own chip (so a quick 1–3 file attach reads cleanly).
          Otherwise → collapse into a SINGLE folder chip with a count
          + total size, expandable on click. This keeps the chat
          visible when a student dumps an entire repo into the chat.
       */}
      {(pendingFile || chatFiles.length > 0) && (() => {
        const hasFolder = chatFiles.some(f => (f.path || "").includes("/"));
        const collapseFiles = chatFiles.length > 4 || hasFolder;
        const totalBytes = chatFiles.reduce((n, f) => n + (f.size || 0), 0);
        // Common path prefix (folder name) when collapsed.
        let folderLabel = "files";
        if (chatFiles.length > 0) {
          const paths = chatFiles.map(f => f.path || f.name);
          const first = paths[0] || "";
          const slash = first.indexOf("/");
          if (slash > 0 && paths.every(p => p.startsWith(first.slice(0, slash + 1)))) {
            folderLabel = first.slice(0, slash);
          } else if (hasFolder) {
            folderLabel = "mixed folders";
          } else {
            folderLabel = `${chatFiles.length} files`;
          }
        }
        const textCount = chatFiles.filter(f => f.kind === "text").length;
        const binaryCount = chatFiles.filter(f => f.kind === "binary").length;
        return (
          <div style={{padding:"8px 18px 0"}}>
            <div style={{display:"flex",flexWrap:"wrap",gap:6,alignItems:"center"}}>
              {pendingFile && (
                <div style={{padding:"6px 10px",borderRadius:8,background:"rgba(55,138,221,0.10)",border:"1px solid rgba(55,138,221,0.20)",display:"inline-flex",alignItems:"center",gap:6,fontSize:11,maxWidth:260}}>
                  <span>{pendingFile.type==="application/pdf"?"📄":"🖼️"}</span>
                  <span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",color:"#63b3ed"}}>{pendingFile.name}</span>
                  <span style={{color:"#555",fontSize:10}}>{(pendingFile.size/1024).toFixed(0)}KB</span>
                  <button onClick={()=>setPendingFile(null)} style={{background:"none",border:"none",color:"#6a6a7a",cursor:"pointer",fontSize:13,padding:0}}>✕</button>
                </div>
              )}

              {collapseFiles ? (
                // Collapsed: single folder chip summarizing everything.
                <div
                  onClick={() => setChatFilesExpanded(v => !v)}
                  title="Click to expand the file list"
                  style={{
                    padding:"6px 12px", borderRadius:8,
                    background:"rgba(104,211,145,0.10)",
                    border:"1px solid rgba(104,211,145,0.25)",
                    display:"inline-flex", alignItems:"center", gap:8,
                    fontSize:11, cursor:"pointer", userSelect:"none",
                  }}
                >
                  <span style={{fontSize:14}}>📁</span>
                  <span style={{color:"#9ce5b6",fontWeight:600,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",maxWidth:200}}>
                    {folderLabel}
                  </span>
                  <span style={{color:"#9ce5b6",fontSize:10}}>{chatFiles.length} file{chatFiles.length===1?"":"s"}</span>
                  <span style={{color:"#555",fontSize:10}}>·</span>
                  <span style={{color:"#555",fontSize:10}}>
                    {textCount > 0 && `${textCount} text`}
                    {textCount > 0 && binaryCount > 0 && " + "}
                    {binaryCount > 0 && `${binaryCount} binary`}
                  </span>
                  <span style={{color:"#555",fontSize:10}}>·</span>
                  <span style={{color:"#555",fontSize:10}}>{(totalBytes/1024).toFixed(0)}KB</span>
                  <span style={{color:"#6a8ab5",fontSize:10,marginLeft:4}}>
                    {chatFilesExpanded ? "▾ hide" : "▸ show"}
                  </span>
                  <button
                    onClick={(e) => { e.stopPropagation(); clearChatFiles(); }}
                    title="Remove all attached files"
                    style={{background:"none",border:"none",color:"#6a8ab5",cursor:"pointer",fontSize:13,padding:0,marginLeft:2}}
                  >✕</button>
                </div>
              ) : (
                // Inline: small N — render each chip directly.
                chatFiles.map((f, i) => {
                  const icon = f.extractedFrom === "docx" || f.extractedFrom === "doc" ? "📘"
                    : f.kind === "text" ? "📄"
                    : f.mediaType === "application/pdf" ? "📕"
                    : (f.mediaType || "").startsWith("image/") ? "🖼️"
                    : "📎";
                  const color = f.kind === "text" ? "#9ce5b6" : "#63b3ed";
                  const bg = f.kind === "text" ? "rgba(104,211,145,0.08)" : "rgba(55,138,221,0.10)";
                  const border = f.kind === "text" ? "rgba(104,211,145,0.20)" : "rgba(55,138,221,0.20)";
                  return (
                    <div key={`${f.path}-${i}`}
                      title={`${f.path} (${f.kind === "text" ? "text" : f.mediaType})`}
                      style={{padding:"6px 10px",borderRadius:8,background:bg,border:`1px solid ${border}`,display:"inline-flex",alignItems:"center",gap:6,fontSize:11,maxWidth:260}}>
                      <span>{icon}</span>
                      <span style={{overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",color}}>{f.path}</span>
                      <span style={{color:"#555",fontSize:10}}>{(f.size/1024).toFixed(0)}KB</span>
                      <button onClick={()=>removeChatFile(i)} style={{background:"none",border:"none",color:"#6a6a7a",cursor:"pointer",fontSize:13,padding:0}}>✕</button>
                    </div>
                  );
                })
              )}
            </div>

            {/* Expanded list — appears under the folder chip when
                the student clicks it. Scrollable so 100s of files
                don't blow out the chat layout. */}
            {collapseFiles && chatFilesExpanded && (
              <div style={{
                marginTop:6, padding:"8px 10px",
                borderRadius:8,
                background:"rgba(255,255,255,0.02)",
                border:"1px solid rgba(255,255,255,0.04)",
                maxHeight:140, overflowY:"auto",
                display:"flex", flexDirection:"column", gap:3,
                fontSize:10.5,
              }}>
                {chatFiles.map((f, i) => {
                  const icon = f.extractedFrom === "docx" || f.extractedFrom === "doc" ? "📘"
                    : f.kind === "text" ? "📄"
                    : f.mediaType === "application/pdf" ? "📕"
                    : (f.mediaType || "").startsWith("image/") ? "🖼️"
                    : "📎";
                  const color = f.kind === "text" ? "#9ce5b6" : "#63b3ed";
                  return (
                    <div key={`exp-${f.path}-${i}`} style={{display:"flex",alignItems:"center",gap:6}}>
                      <span>{icon}</span>
                      <span style={{flex:1,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",color}}>{f.path}</span>
                      <span style={{color:"#555"}}>{(f.size/1024).toFixed(0)}KB</span>
                      <button onClick={()=>removeChatFile(i)} title="Remove" style={{background:"none",border:"none",color:"#6a6a7a",cursor:"pointer",fontSize:12,padding:0}}>✕</button>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        );
      })()}

      <div style={{padding:"14px 18px",borderTop:"1px solid rgba(255,255,255,0.05)",flexShrink:0}}>
        {councilDecisionType && (
          <div role="status" style={{
            marginBottom:10,
            padding:"10px 12px",
            borderRadius:10,
            border:"1px solid rgba(167,139,250,0.35)",
            background:"rgba(167,139,250,0.08)",
            color:"#d8ccff",
            fontSize:11,
            lineHeight:1.55,
          }}>
            <div style={{display:"flex",gap:10,alignItems:"center",flexWrap:"wrap",marginBottom:6}}>
              <strong>{locale === "ko" ? "전략 위원회 - 다음 메시지 1회" : "Strategy Council - next message only"}</strong>
              <select
                aria-label={locale === "ko" ? "전략 결정 유형" : "Strategy decision type"}
                value={councilDecisionType}
                onChange={(event) => setCouncilDecisionType(event.target.value)}
                style={{padding:"5px 30px 5px 9px",borderRadius:7,border:"1px solid rgba(167,139,250,0.35)",backgroundColor:"#17132a",color:"#e8e2ff",fontSize:11}}
              >
                {COUNCIL_DECISION_OPTIONS.map((option) => (
                  <option key={option.value} value={option.value}>
                    {locale === "ko" ? option.labelKo : option.label}
                  </option>
                ))}
              </select>
              <button
                type="button"
                onClick={() => setCouncilDecisionType(null)}
                style={{marginLeft:"auto",padding:"4px 9px",borderRadius:7,border:"1px solid rgba(167,139,250,0.25)",background:"transparent",color:"#c4b5fd",fontSize:10,cursor:"pointer"}}
              >
                {locale === "ko" ? "취소" : "Cancel mode"}
              </button>
            </div>
            <div>
              {locale === "ko"
                ? "4개의 AI 검토 단계와 결정론적 조정자를 실행합니다. 일반 채팅보다 느리며 월간 AI 예산을 사용합니다."
                : "Runs four AI review stages plus a deterministic moderator. It is slower than ordinary chat and uses your monthly AI budget."}
              {budgetStatus?.remainingUsd != null
                ? (locale === "ko"
                  ? ` 남은 예산: $${Number(budgetStatus.remainingUsd).toFixed(2)}.`
                  : ` $${Number(budgetStatus.remainingUsd).toFixed(2)} remains.`)
                : ""}
            </div>
            <div style={{marginTop:4,color:"#aa9ed3"}}>
              {locale === "ko"
                ? `첨부 파일은 사용할 수 없습니다. ${input.length.toLocaleString()}/2,000자`
                : `Attachments are unavailable. ${input.length.toLocaleString()}/2,000 characters.`}
            </div>
          </div>
        )}
        <div style={{display:"flex",gap:8,alignItems:"flex-end"}}>
          {/* File upload (single, legacy + multi via attribute) */}
          <input type="file" ref={fileInputRef} multiple accept=".pdf,.png,.jpg,.jpeg,.webp,.gif,.doc,.docx,.txt,.md,.markdown,.csv,.tsv,.json,.jsonl,.yaml,.yml,.xml,.html,.htm,.css,.scss,.py,.js,.mjs,.cjs,.jsx,.ts,.tsx,.go,.rs,.java,.kt,.c,.cc,.cpp,.h,.hpp,.cs,.php,.rb,.swift,.sh,.bash,.zsh,.ps1,.sql,.r,.lua,.dart,.vue,.svelte,.log,.env,.ini,.toml,.conf,.cfg,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/msword" onChange={handleChatFilesSelect} style={{display:"none"}} />
          <button onClick={()=>fileInputRef.current?.click()} disabled={loading||Boolean(councilDecisionType)} title={councilDecisionType ? "Attachments are unavailable in Strategy Council mode" : "Attach files (PDF, image, text, code) — multiple allowed"} style={{padding:"10px 12px",borderRadius:12,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:(pendingFile||chatFiles.length>0)?"#63b3ed":"#6a6a7a",fontSize:16,cursor:loading||councilDecisionType?"default":"pointer",flexShrink:0,transition:"all 0.15s",alignSelf:"flex-end",height:42}}>📎</button>
          {/* Folder upload — second button per user request */}
          <input type="file" ref={folderInputRef} webkitdirectory="" directory="" multiple onChange={handleChatFilesSelect} style={{display:"none"}} />
          <button onClick={()=>folderInputRef.current?.click()} disabled={loading||Boolean(councilDecisionType)} title={councilDecisionType ? "Attachments are unavailable in Strategy Council mode" : "Attach an entire folder — text/code files included"} style={{padding:"10px 12px",borderRadius:12,border:"1px solid rgba(255,255,255,0.08)",background:"transparent",color:chatFiles.some(f=>f.path&&f.path.includes("/"))?"#9ce5b6":"#6a6a7a",fontSize:16,cursor:loading||councilDecisionType?"default":"pointer",flexShrink:0,transition:"all 0.15s",alignSelf:"flex-end",height:42}}>📁</button>
          {/* Auto-extending textarea. Grows vertically on input up to
              ~40 vh; the outer flex container handles word-wrap and
              screen-width responsiveness automatically. Enter sends;
              Shift+Enter inserts a newline. */}
          <textarea
            ref={chatTextareaRef}
            value={input}
            onChange={e => {
              setInput(e.target.value);
              // Auto-resize: reset height to read true scrollHeight,
              // then clamp between min and max.
              const el = e.target;
              el.style.height = "auto";
              const maxH = Math.max(120, Math.floor(window.innerHeight * 0.4));
              el.style.height = Math.min(maxH, Math.max(42, el.scrollHeight)) + "px";
            }}
            onKeyDown={e => {
              if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); send(); }
            }}
            placeholder={councilDecisionType
              ? (locale === "ko" ? "위원회가 검토할 독립적인 질문을 입력하세요..." : "Enter one self-contained decision question for the Council...")
              : (pendingFile||chatFiles.length>0) ? "Ask the model about the attached file(s)…" : "Ask about academics, ECs, colleges, or strategy… (Shift+Enter for newline)"}
            disabled={loading}
            maxLength={councilDecisionType ? 2000 : undefined}
            rows={1}
            style={{
              flex:1, minHeight:42, maxHeight:"40vh",
              padding:"11px 14px", borderRadius:12,
              border:"1px solid rgba(255,255,255,0.08)",
              background:"rgba(255,255,255,0.03)",
              color:"#e8e6e3", fontSize:14, outline:"none",
              resize:"none", lineHeight:1.45, fontFamily:"inherit",
              overflowY:"auto", boxSizing:"border-box",
              width:"100%",
            }}
          />
          <button onClick={send} disabled={loading||(!input.trim()&&!pendingFile&&chatFiles.length===0)} style={{padding:"12px 20px",borderRadius:12,border:"none",background:loading||(!input.trim()&&!pendingFile&&chatFiles.length===0)?"rgba(255,255,255,0.03)":councilDecisionType?"linear-gradient(135deg,#7F77DD,#a855f7)":"linear-gradient(135deg,#378ADD,#667eea)",color:loading||(!input.trim()&&!pendingFile&&chatFiles.length===0)?"#444":"#fff",fontSize:14,fontWeight:600,cursor:loading||(!input.trim()&&!pendingFile&&chatFiles.length===0)?"default":"pointer",alignSelf:"flex-end",height:42,whiteSpace:"nowrap"}}>{councilDecisionType ? (locale === "ko" ? "위원회 소집" : "Convene Council") : "Send"}</button>
        </div>
        {/* ─── Inline tool launchers ─── */}
        {/* Open each tool as an inline card in the conversation. These   */}
        {/* live here (per chat), not in the sidebar, per the inline-tools */}
        {/* design. openTool appends an ephemeral role:"tool" message.    */}
        <div className="cc-quick-actions" style={{display:"flex",gap:6,marginTop:10,flexWrap:"wrap",alignItems:"center"}}>
          <button
            type="button"
            onClick={() => setCouncilDecisionType((current) => {
              if (current) return null;
              return "course-selection";
            })}
            disabled={loading || Boolean(pendingFile) || chatFiles.length > 0}
            title={(pendingFile || chatFiles.length > 0)
              ? "Remove attachments before enabling Strategy Council"
              : "Explicitly use four AI reviewers plus a deterministic moderator for your next decision question"}
            aria-pressed={Boolean(councilDecisionType)}
            style={{
              padding:"5px 11px",
              borderRadius:8,
              border:`1px solid ${councilDecisionType ? "rgba(167,139,250,0.65)" : "rgba(167,139,250,0.25)"}`,
              background:councilDecisionType ? "rgba(167,139,250,0.18)" : "rgba(167,139,250,0.06)",
              color:councilDecisionType ? "#e8e2ff" : "#c4b5fd",
              fontSize:11,
              fontWeight:700,
              cursor:loading || pendingFile || chatFiles.length > 0 ? "default" : "pointer",
              opacity:loading || pendingFile || chatFiles.length > 0 ? 0.5 : 1,
            }}
          >
            {locale === "ko" ? "전략 위원회" : "Strategy Council"}
          </button>
          {[
            {tool:"narrative",  key:"chat.tools.narrative"},
            {tool:"candidates", key:"chat.tools.candidates"},
            {tool:"spike",      key:"chat.tools.spike"},
            {tool:"courses",    key:"chat.tools.courses"},
          ].map(({tool,key})=>(
            <button key={tool} onClick={()=>openTool(tool)} style={{padding:"5px 11px",borderRadius:8,border:"1px solid rgba(104,211,145,0.18)",background:"rgba(104,211,145,0.06)",color:"#9ce5b6",fontSize:11,fontWeight:600,cursor:"pointer",transition:"all 0.15s"}}
              onMouseEnter={e=>{e.currentTarget.style.borderColor="rgba(104,211,145,0.45)"}}
              onMouseLeave={e=>{e.currentTarget.style.borderColor="rgba(104,211,145,0.18)"}}>{tt(locale, key)}</button>
          ))}
        </div>
        <div className="cc-quick-actions" style={{display:"flex",gap:5,marginTop:8,flexWrap:"wrap",alignItems:"center"}}>
          <span style={{fontSize:10,color:"#444",marginRight:2}}>📎 PDF, DOCX, TXT/MD, images</span>
          <span style={{color:"rgba(255,255,255,0.06)"}}>|</span>
          {["What's my profile?","Suggest ECs for me","Search colleges for CS","Plan my junior year"].map(q=>(
            <button key={q} onClick={()=>{setInput(q);setTimeout(()=>(chatTextareaRef.current||inputRef.current)?.focus(),50)}} style={{padding:"3px 9px",borderRadius:7,border:"1px solid rgba(255,255,255,0.05)",background:"transparent",color:"#6a6a7a",fontSize:10.5,cursor:"pointer",transition:"all 0.15s"}}
              onMouseEnter={e=>{e.target.style.borderColor="rgba(55,138,221,0.3)";e.target.style.color="#63b3ed"}}
              onMouseLeave={e=>{e.target.style.borderColor="rgba(255,255,255,0.05)";e.target.style.color="#6a6a7a"}}>{q}</button>
          ))}
        </div>
      </div>
    </main>
  );
}
